version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "yarn"
    directory: "/vue-client"
    schedule:
      interval: "daily"
